server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/contasys_db
    username: contasys_user
    password: 123456

  jpa:
    hibernate:
      ddl-auto: none

    show-sql: true

    properties:
      hibernate:
        format_sql: true

  jackson:
    time-zone: America/Lima

springdoc:
  api-docs:
    path: /api-docs

  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret: contasysSecretKeyContasysSecretKey123456
  expiration: 86400000